core/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from . import views
from .forms import UserLoginForm

app_name = 'accounts'

urlpatterns = [
    path('', views.AccountPage.as_view(), name='account'),
    path('personal_information/', views.AccountPersonalInformation.as_view(), name='personal_information'),
    path('personal_orders/', views.AccountPersonalOrders.as_view(), name='personal_orders'),
    path('edit_information/', views.EditPersonalInformation.as_view(), name='edit_information'),


    path('registration/', views.AccountRegistrationView.as_view(),
         name='account_registration'),
    path('activate/<slug:uidb64>/<slug:token>)/',
         views.account_activate, name='activate_account'),
    path('login/', auth_view.LoginView.as_view(template_name='accounts/registration/login.html',
         form_class=UserLoginForm), name='login'),
    path('logout/', auth_view.LogoutView.as_view(next_page='/account/login/'), name='logout'),
]

core/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add-to-cart/<slug:ct_model>/<slug:product_slug>',
         views.AddToCartView.as_view(), name='add_to_cart'),
    path('delete-from-cart/<slug:ct_model>/<slug:product_slug>/',
         views.DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-product-quantity/<slug:ct_model>/<slug:product_slug>/',
         views.ChangeQuantityView.as_view(), name='change_product_quantity'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='card')),
    path('order/', include('orders.urls', namespace='orders')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/coupons/urls.py
from django.urls import path

from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.ApplyCouponView.as_view(), name='apply_coupon'),
]

core/orders/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'orders'


urlpatterns = [
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('create_order/', views.CreateOrderView.as_view(), name='create_order'),
    path('invalid_order/', TemplateView.as_view(template_name='orders/order_invalid.html'), name='invalid_order'),

]

core/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.BaseView.as_view(), name='home_page'),

    path('search/', views.search_product, name='search'),

    path('products/', views.ProductListView.as_view(), name='products_list'),

    path('products/price/<str:min_price>/<str:max_price>/',
         views.ProductListView.as_view(), name='product_list_by_price'),


    path('products/category/<slug:category_slug>/',
         views.ProductListView.as_view(), name='product_list_by_category'),

    path('products/brand/<slug:brand_slug>/', views.ProductListView.as_view(),
         name='product_list_by_brand'),



    path('product/<slug:ct_model>/<slug:product_slug>/',
         views.ProductDetailView.as_view(), name='product_detail'),
]

core/cart/models.py
from django.db import models

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from coupons.models import Coupon
from accounts.models import *


class CartProduct(models.Model):
    """ Product model for cart """

    user = models.ForeignKey(
        'accounts.UserBase', on_delete=models.CASCADE, verbose_name='Покупець')
    cart = models.ForeignKey('cart.Cart', on_delete=models.CASCADE,
                             verbose_name='Корзина', related_name='related_products')

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    quantity = models.PositiveIntegerField(default=1, verbose_name="Кількість")
    user_size_choice = models.CharField(
        max_length=255, null=True, verbose_name='Вибраний користовачем розмір')

    final_price = models.DecimalField(
        max_digits=9, decimal_places=2, blank=True, verbose_name='Ціна')

    def save(self, *args, **kwargs):
        if self.content_object.discount_price:
            self.final_price = self.quantity * self.content_object.discount_price
        else:
            self.final_price = self.quantity * self.content_object.price
        super().save(*args, **kwargs)

    def get_model_name(self):
        return self.__class__._meta.model_name

    def __str__(self):
        return f'Продукт (для корзини) для покупця {self.user}'

    class Meta:
        verbose_name = 'Продукти для корзини'
        verbose_name_plural = 'Продукт для корзини'


class Cart(models.Model):
    """ Cart model """

    owner = models.ForeignKey(
        'accounts.UserBase', on_delete=models.CASCADE, verbose_name='Власник', null=True)
    products = models.ManyToManyField(
        CartProduct, blank=True, related_name='related_cart', verbose_name="Продукти")
    total_products = models.PositiveIntegerField(
        default=0, verbose_name='Кількість продуктів')
    final_price = models.DecimalField(
        default=0, max_digits=9, decimal_places=2, verbose_name='Фінальна ціна')
    in_order = models.BooleanField(default=False, verbose_name="В обробці")
    for_anonymos_user = models.BooleanField(
        default=False, verbose_name="Для не авторизованих користувачів")
    coupons = models.ManyToManyField(Coupon, related_name='related_coupons')

    def __str__(self):
        return f'Корзина для покупця {self.owner}'

    class Meta:
        verbose_name_plural = 'Корзина'
        verbose_name_plural = 'Корзини'

core/cart/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib import messages

from django.views.generic import View
from store.services import ProductSystem

from coupons.forms import CouponApplyForm
from coupons.services import CouponSystem

from .mixins import CartMixin
from .services import CartSystem


class AddToCartView(CartMixin, View):
    """ Add product to customer cart """

    def post(self, request, **kwargs):
        if self.cart.for_anonymos_user:
            messages.add_message(request, messages.SUCCESS,
                                 "Добавлення товару до корзини доступно лише авторизованим користувачам!")
            return redirect('store:products_list')

        cart_product, create = CartSystem.get_or_create_cart_product(
            self=ProductSystem,
            cart=self.cart, kwargs=kwargs)
        CartSystem.add_product_to_cart(self=CartSystem, request=request,
                                       cart_product=cart_product, create=create)
        CartSystem.save_cart(cart=self.cart)

        CartSystem.recal_total_products_in_cart(
            self=CartSystem, cart=self.cart)
        messages.add_message(request, messages.SUCCESS,
                             "Товар успішно додано в корзину")
        return redirect('store:products_list')


class DeleteFromCartView(CartMixin, View):
    """ Delete product from customer cart """

    def get(self, request, **kwargs):

        cart_product = CartSystem.get_cart_product(
            self=ProductSystem,
            cart=self.cart, kwargs=kwargs
        )

        CartSystem.remove_product_from_cart(
            self=CartSystem, cart_product=cart_product)
        CartSystem.recal_total_products_in_cart(
            self=CartSystem, cart=self.cart)
        messages.add_message(request, messages.WARNING,
                             "Товар успішно видалено з корзини")
        return HttpResponseRedirect('/cart/')


class ChangeQuantityView(CartMixin, View):
    """ Change product quantity in customer cart """

    def post(self, request, **kwargs):
        cart_product = CartSystem.get_cart_product(
            self=ProductSystem, cart=self.cart, kwargs=kwargs
        )

        CartSystem.change_product_quantity(
            self=CartSystem, request=request, cart_product=cart_product)
        CartSystem.recal_total_products_in_cart(
            self=CartSystem, cart=self.cart)
        messages.add_message(request, messages.INFO,
                             "Кількість товару успішно змінено!")
        return HttpResponseRedirect('/cart/')


class CartView(CartMixin, View):
    """ Show customer cart page """

    def get(self, request):
        coupon_form = CouponApplyForm()
        coupons = CouponSystem.get_coupons_applied_to_cart(cart=self.cart)
        return render(request, 'cart/cart_page.html', {'cart': self.cart,
                                                       'coupon_form': coupon_form,
                                                       'coupons': coupons})

core/templates/cart/cart_page.html
{% extends '../store/base.html' %}
{% load static %}
{% block content %}


<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <div class="breadcrumb__links">
                        <h4>Корзина</h4>
                        <a href="{% url 'store:home_page' %}">Головна</a>
                        <a href="{% url 'store:products_list' %}">Продукти</a>
                        <span>Корзина</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Breadcrumb Section End -->
{% if request.user.is_authenticated %}
<!-- Shopping Cart Section Begin -->
<section class="shopping-cart spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="shopping__cart__table">
                    <table>
                        {% if cart.products.all %}
                        <thead>
                            <tr>
                                <th>Продукт</th>
                                <th>Кількість</th>
                                <th>Всього</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart.products.all|dictsort:"content_object.price" %}
                            <tr>
                                <td class="product__cart__item">
                                    <div class="product__cart__item__pic">
                                        <img style="max-height:150px;"
                                            src="{% if item.content_object.image %}{{item.content_object.image.url}}{% else %}{% static 'img/default/default.jpg'%}{% endif %}"
                                            alt="">
                                    </div>
                                    <div class="product__cart__item__text">
                                        <h6>{{item.content_object.name}} {{item.content_object.brand}}</h6>
                                        {% if item.content_object.discount_price %}
                                        <h5>{{item.content_object.discount_price}} грн</h5>
                                        {% else %}
                                        <h5>{{item.content_object.price}} грн</h5>
                                        {% endif %}
                                        <h6>Розмір: {{item.user_size_choice}}</h6>
                                    </div>
                                </td>
                                <td class="quantity__item">
                                    <div class="quantity">
                                        <form
                                            action="{% url 'cart:change_product_quantity' ct_model=item.content_object.get_model_name product_slug=item.content_object.slug %}"
                                            method="POST">{% csrf_token %}
                                            <div class="pro-qty-2">
                                                <input type="text" name="product_quantity" value="{{item.quantity}}"
                                                    min="1">
                                            </div>
                                            <input class='update_button' type="submit" value='Оновити' />

                                        </form>
                                    </div>
                                </td>
                                <td class="cart__price">{{item.final_price}} грн</td>
                                <td class="cart__close"><a
                                        href="{% url 'cart:delete_from_cart' ct_model=item.content_object.get_model_name product_slug=item.content_object.slug %}"><i
                                            class="fa fa-close"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        {% else %}
                        <h3>Корзина порожня.</h3>
                        {% endif %}
                    </table>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="continue__btn">
                            <a href="{% url 'store:products_list' %}">Повернутися до продуктів</a>
                        </div>
                    </div>
                    {% if cart.products.all %}
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cart__discount">
                    <h6>Промокод</h6>
                    <form action="{% url 'coupons:apply_coupon' %}" method="POST">{% csrf_token %}
                        {{coupon_form.code}}
                        <input type="submit" class='cart__discount_button' value="Застосувати">
                    </form>
                </div>
                <div class="cart__total">
                    {% if coupons %}
                    <h6>Застосовані купони</h6>
                    <ul>
                        {% for coupon in coupons %}
                        <li>Купон "{{coupon}}"<span>Знижка - {{coupon.discount}}%</span></li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    <hr>
                    <h6>Загальна вартісь</h6>
                    <ul>
                        <li>Всього <span>{{cart.final_price}} грн.</span></li>
                    </ul>
                    <a href="{% url 'orders:checkout' %}" class="primary-btn">Оформити замовлення</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% else %}
<section class="shopping-cart spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Корзина доступна лише для авторизованих користувачів.</h3>
                <h6>Будь ласка, зайдіть в свій акаунт <a href="{% url 'accounts:login' %}">авторизуватися</a></h6>

            </div>
        </div>
</section>
{% endif %}
{% endblock content %}