core/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from . import views
from .forms import UserLoginForm

app_name = 'accounts'

urlpatterns = [
    path('', views.AccountPage.as_view(), name='account'),
    path('personal_information/', views.AccountPersonalInformation.as_view(), name='personal_information'),
    path('personal_orders/', views.AccountPersonalOrders.as_view(), name='personal_orders'),
    path('edit_information/', views.EditPersonalInformation.as_view(), name='edit_information'),


    path('registration/', views.AccountRegistrationView.as_view(),
         name='account_registration'),
    path('activate/<slug:uidb64>/<slug:token>)/',
         views.account_activate, name='activate_account'),
    path('login/', auth_view.LoginView.as_view(template_name='accounts/registration/login.html',
         form_class=UserLoginForm), name='login'),
    path('logout/', auth_view.LogoutView.as_view(next_page='/account/login/'), name='logout'),
]

core/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add-to-cart/<slug:ct_model>/<slug:product_slug>',
         views.AddToCartView.as_view(), name='add_to_cart'),
    path('delete-from-cart/<slug:ct_model>/<slug:product_slug>/',
         views.DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-product-quantity/<slug:ct_model>/<slug:product_slug>/',
         views.ChangeQuantityView.as_view(), name='change_product_quantity'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='card')),
    path('order/', include('orders.urls', namespace='orders')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.BaseView.as_view(), name='home_page'),

    path('search/', views.search_product, name='search'),

    path('products/', views.ProductListView.as_view(), name='products_list'),

    path('products/price/<str:min_price>/<str:max_price>/',
         views.ProductListView.as_view(), name='product_list_by_price'),


    path('products/category/<slug:category_slug>/',
         views.ProductListView.as_view(), name='product_list_by_category'),

    path('products/brand/<slug:brand_slug>/', views.ProductListView.as_view(),
         name='product_list_by_brand'),



    path('product/<slug:ct_model>/<slug:product_slug>/',
         views.ProductDetailView.as_view(), name='product_detail'),
]

core/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

from django.core.mail import send_mail

from phonenumber_field.modelfields import PhoneNumberField
from cities_light.models import City

from orders.models import *


class CustomAccountManager(BaseUserManager):
    """ Custom create user account """

    def create_superuser(self, email, first_name, last_name, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError('Адмін повинен мати параметр is_staff=True.')

        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Адмін повинен мати параметр is_superuser=True.')

        return self.create_user(email, first_name, last_name, password, **other_fields)

    def create_user(self, email, first_name, last_name, password, **other_fields):
        if not email:
            raise ValueError('Ви повинні вказати Електронну адресу')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name,
                          last_name=last_name, **other_fields)
        user.set_password(password)
        user.save()
        return user


class UserBase(AbstractBaseUser, PermissionsMixin):
    """ Custom user model """
    email = models.EmailField(unique=True, verbose_name="Електронна адреса")
    phone = PhoneNumberField(unique=True, blank=True,
                             verbose_name="Номер телефону")

    first_name = models.CharField(
        max_length=150, blank=True, verbose_name="Ім'я")
    last_name = models.CharField(
        max_length=150, blank=True, verbose_name="Фамілія")

    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True, verbose_name="Місто")

    orders = models.ManyToManyField(
        'orders.Order', related_name="related_order", verbose_name="Замовлення покупця", blank=True)

    # User status
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    class Meta:
        verbose_name = 'Акаунт'
        verbose_name_plural = 'Акаунти'

    def __str__(self):
        return self.email

    # Send email token for ragistration
    def email_user(self, subject, message):
        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [self.email],
            fail_silently=False,
        )

core/orders/models.py
from django.db import models
from django.utils import timezone

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from cities_light.models import City

from cart.models import *
from accounts.models import *


class OrderItem(models.Model):
    """ Item model for order """

    order = models.ForeignKey(
        'Order', on_delete=models.CASCADE, verbose_name="Замовлення")

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    price = models.DecimalField(
        max_digits=9, decimal_places=2, verbose_name="Ціна")
    quantity = models.PositiveIntegerField(default=1, verbose_name="Кількість")

    def __str__(self):
        return str(self.id)


class Order(models.Model):
    """ Order model """

    STATUS_CHOICES = (
        ("STATUS_NEW", "Нове замовлення"),
        ("STATUS_IN_PROCESS", "Замовлення в процесі обробки"),
        ("STATUS_READY", "Замовлення готове"),
        ("STATUS_COMPLETED", "Замовлення виконане"),
    )

    BYING_TYPE = (
        ("BYING_TYPE_SELF", "Самовивіз"),
        ("BYING_TYPE_DELIVERY", "Доставка"),
    )

    customer = models.ForeignKey(
        'accounts.UserBase', on_delete=models.CASCADE, related_name="related_orders", verbose_name='Покупець')
    cart = models.ForeignKey(
        'cart.Cart', on_delete=models.CASCADE, verbose_name="Корзина", null=True
    )
    first_name = models.CharField(max_length=255,  verbose_name="Ім'я")
    last_name = models.CharField(max_length=255,  verbose_name="Фамілія")
    phone = models.CharField(max_length=255,  verbose_name="Номер телефону")
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name="Місто")
    post_office = models.CharField(
        max_length=255, verbose_name="Вдділення пошти")
    email = models.EmailField()
    comment = models.TextField(
        null=True, blank=True, verbose_name="Комментар до замовлення")

    status = models.CharField(
        max_length=255, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][1], verbose_name="Статус")

    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата створення замовлення")
    order_date = models.DateTimeField(
        default=timezone.now, verbose_name="Дата доставки товару покупцю")

    class Meta:
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'

    def __str__(self):
        return str(self.id)

core/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from phonenumber_field.formfields import PhoneNumberField

from .models import UserBase


class UserLoginForm(AuthenticationForm):
    username = forms.EmailField()  # Email
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    phone = PhoneNumberField(widget=forms.TextInput(
        attrs={'placeholder': '+380(11)9999999', 'maxlength': 18}))
    phone.error_messages['invalid'] = 'Введіть коректний номер телефону (наприклад, +380(11)9999999).'

    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = UserBase
        widgets = {
            'email': forms.TextInput(
                attrs={'placeholder': 'example@gmail.com', 'maxlength': 30}
            ),
            'first_name': forms.TextInput(
                attrs={'placeholder': 'Тест', 'maxlength': 30}
            ),
            'last_name': forms.TextInput(
                attrs={'placeholder': 'Тестов', 'maxlength': 30}
            ),
        }
        fields = ('email', 'first_name', 'last_name', 'city')

    def clean_password2(self):
        if self.cleaned_data['password'] != self.cleaned_data['password2']:
            raise forms.ValidationError("Пароль не збігається.")
        return self.cleaned_data['password2']

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        e = UserBase.objects.filter(email=email)
        if e.count():
            raise forms.ValidationError(
                "Акаунт з таким електронним адресом вже існує!")
        return email



class EditPersonalInformationForm(forms.ModelForm):
    class Meta:
        model = UserBase
        fields = ('email', 'first_name', 'last_name', 'city', 'phone')

core/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.views.generic.base import View

from .forms import RegistrationForm, EditPersonalInformationForm
from .token import account_activation_token
from .services import AccountSystem


from orders.services import  OrderSystem
from cart.services import CartSystem


@method_decorator(login_required, name='dispatch')
class AccountPage(View):
    """ Show customer account page """

    def get(self, request):
        customer = AccountSystem.get_customer_account(request)
        return render(request, 'accounts/account.html', {'customer': customer, })


@method_decorator(login_required, name='dispatch')
class AccountPersonalInformation(View):
    """ Show customer personal information page """

    def get(self, request):
        customer = AccountSystem.get_customer_account(request)
        return render(request, 'accounts/account_personal_information.html', {'customer': customer})


class EditPersonalInformation(View):
    """ Edit customer personal information """

    def post(self, request):
        user_edit_form = EditPersonalInformationForm(
            request.POST, instance=request.user)
        AccountSystem.validate_personal_edit_data(form=user_edit_form)
        return redirect('/account/personal_information/')

    def get(self, request):
        user_edit_form = EditPersonalInformationForm(instance=request.user)
        return render(request, 'accounts/account_personal_information_edit.html', {'form': user_edit_form})


class AccountPersonalOrders(View):
    """ Show customer orders """

    def get(self, request):
        customer = AccountSystem.get_customer_account(request)
        carts = CartSystem.get_customer_in_order_carts(customer=customer)
        orders = OrderSystem.get_user_orders(customer=customer, cart=carts)
        order_items = OrderSystem.get_order_items()
        return render(request, 'accounts/account_orders.html', {'orders': orders, 'order_items': order_items})


class AccountRegistrationView(View):
    """ Registration customer account """

    def post(self, request):
        form = RegistrationForm(request.POST)
        form = AccountSystem.registration(
            self=AccountSystem, request=request, form=form)
        if form.errors:
            return render(request, 'accounts/registration/registration.html', {'form': form})
        else:
            return render(request, 'accounts/registration/registration_valid.html')


    def get(self, request):
        if request.user.is_authenticated:
            return redirect('accounts:account')
        form = RegistrationForm()
        return render(request, 'accounts/registration/registration.html', {'form': form})


def account_activate(request, uidb64, token):
    """ Activation customer account using token """

    try:
        user = AccountSystem.get_user_uid(uidb64=uidb64)
    except(TypeError, ValueError, OverflowError):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        AccountSystem.activation_customer_account(request, user=user)
        return redirect('accounts:account')
    else:
        messages.add_message(request, messages.SUCCESS,
                             "Невдала спроба активації вашого акаунту, повторіть спробу")
        return redirect('accounts:account_registration')

core/templates/accounts/account.html
{% extends '../store/base.html' %}
{% load static %}
{% block content %}


<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <div class="breadcrumb__links">
                        <h4>Ваш профіль</h4>
                        <a href="{% url 'store:home_page' %}">Головна</a>
                        <a href="{% url 'store:products_list' %}">Продукти</a>
                        <span>Ваш профіль</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Shopping Cart Section Begin -->
{% if request.user.is_authenticated %}
<section class="spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="account__menu">
                    <ul class="filter__controls">

                        <li {% if request.path == '/account/' %}class='active' {% endif %}>
                            <a href="{% url 'accounts:account' %}">Профіль</a>
                        </li>
                        <li {% if request.path == '/account/personal_orders/' %}class='active' {% endif %}>
                            <a href="{% url 'accounts:personal_orders' %}">Замовлення</a>
                        </li>
                        <li {% if request.path == '/account/personal_information/'%}class='active' {% endif %}>
                            <a href="{% url 'accounts:personal_information' %}">Персональна інформація</a>
                        </li>
                    </ul>
                        {% block account_content %}
                        <ul>
                            <li><h3>{{customer.first_name|title}} {{customer.last_name|title}}</h3></li>
                            <li><h5>Мобільний телефон {{customer.phone}}</h5></li>
                            <li><h5>Email {{customer}}</h5></li>
                            <li><a href="{% url 'accounts:logout' %}"><img src="{% static 'img/icon/logout.png' %}" alt=""></a></li>
                        </ul>
                        {% endblock account_content %}
                </div>
            </div>
        </div>
    </div>
</section>
{% else %}
<section class="spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Список бажаних товарів доступний тільки авторизованим користувачам.</h3>
                <h6>Будь ласка, зайдіть в свій акаунт <a href="">авторизуватися</a></h6>
            </div>
        </div>
</section>
{% endif %}
<!-- Shopping Cart Section End -->
{% endblock content %}

core/templates/accounts/account_orders.html
{% extends './account.html' %}
{% load static %}

{% block account_content %}
<section class="shopping-cart spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="shopping__cart__table">
                    <hr>
                    <table>
                        <thead>
                            <tr>
                                <th>Номер замовлення</th>
                                <th>Статус</th>
                                <th>Сумма</th>
                                <th>Опис замовлення</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                            <tr>
                                <td class="product__cart__item">
                                    <div> #{{order.id}} </div>
                                </td>
                                <td>
                                    {{order.get_status_display}}
                                </td>
                                <td class="cart__price">{{order.cart.final_price}} грн</td>
                                <td class="order_desc">
                                    <ul>
                                        <li>Опис <img src="{% static 'img/icon/description.png' %}" alt="">
                                            <ul class="dropdown">
                                                {% for order_item in order_items %}
                                                    {% if order_item.order == order %}
                                                        <a href="{{order_item.content_object.get_absolute_url}}"> <h6>{{order_item.content_object}} x{{order_item.quantity}}  {{order_item.price}}грн</h6></a>
                                                        <hr>
                                                    {% endif %}
                                                {% endfor %}
                                            </ul>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock account_content %}

core/templates/accounts/account_personal_information.html
{% extends './account.html' %}
{% load static %}
{% block account_content %}
<div class='col-lg-12'>
    <div class="product__details__last__option">
        <h5><span>Ім'я : {{customer.first_name|title}}</span></h5>
        <h5><span>Фамілія : {{customer.last_name|title}}</span></h5>
        <h5><span>Мобільний телефон : {{customer.phone}}</span></h5>
        <h5><span>Email : {{customer.email}}</span></h5>
        <h5><span>Місто : {{customer.city|title}}</span></h5>
    </div>
    <div>
        <h5 class="account_edit"><a href="{% url 'accounts:edit_information' %}">Редагувати данні <img
                    src="{% static 'img/icon/edit.png' %}" alt=""></a></h5>
    </div>
</div>
{% endblock account_content %}

core/templates/accounts/account_personal_information_edit.html
{% extends './account.html' %}
{% block account_content %}
<section class="checkout spad">
    <div class="container">
        <div class="checkout__form">
            <form action="" method="POST" enctype='multipart/form-data'>{% csrf_token %}
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <h6 class="checkout__title">Ваші данні</h6>
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% endif %}
                        <div class="row">

                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Ім'я</p>
                                    {{form.first_name}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Фамілія</p>
                                    {{form.last_name}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Номер телефону</p>
                                    {{form.phone}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Email</p>
                                    {{form.email}}
                                </div>
                            </div>
                        </div>
                        <input type="submit" class="site-btn" value="Редагувати">
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock account_content %}