core/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from . import views
from .forms import UserLoginForm

app_name = 'accounts'

urlpatterns = [
    path('', views.AccountPage.as_view(), name='account'),
    path('personal_information/', views.AccountPersonalInformation.as_view(), name='personal_information'),
    path('personal_orders/', views.AccountPersonalOrders.as_view(), name='personal_orders'),
    path('edit_information/', views.EditPersonalInformation.as_view(), name='edit_information'),


    path('registration/', views.AccountRegistrationView.as_view(),
         name='account_registration'),
    path('activate/<slug:uidb64>/<slug:token>)/',
         views.account_activate, name='activate_account'),
    path('login/', auth_view.LoginView.as_view(template_name='accounts/registration/login.html',
         form_class=UserLoginForm), name='login'),
    path('logout/', auth_view.LogoutView.as_view(next_page='/account/login/'), name='logout'),
]

core/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add-to-cart/<slug:ct_model>/<slug:product_slug>',
         views.AddToCartView.as_view(), name='add_to_cart'),
    path('delete-from-cart/<slug:ct_model>/<slug:product_slug>/',
         views.DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-product-quantity/<slug:ct_model>/<slug:product_slug>/',
         views.ChangeQuantityView.as_view(), name='change_product_quantity'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='card')),
    path('order/', include('orders.urls', namespace='orders')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.BaseView.as_view(), name='home_page'),

    path('search/', views.search_product, name='search'),

    path('products/', views.ProductListView.as_view(), name='products_list'),

    path('products/price/<str:min_price>/<str:max_price>/',
         views.ProductListView.as_view(), name='product_list_by_price'),


    path('products/category/<slug:category_slug>/',
         views.ProductListView.as_view(), name='product_list_by_category'),

    path('products/brand/<slug:brand_slug>/', views.ProductListView.as_view(),
         name='product_list_by_brand'),



    path('product/<slug:ct_model>/<slug:product_slug>/',
         views.ProductDetailView.as_view(), name='product_detail'),
]

core/wish/urls.py
from django.urls import path

from . import views

app_name = 'wish'

urlpatterns = [
    path('', views.WishView.as_view(), name='wish'),
    path('add-to-wish/<slug:ct_model>/<slug:product_slug>',
         views.AddToWishView.as_view(), name='add_to_wish'),
    path('delete-from-wish/<slug:ct_model>/<slug:product_slug>/',
         views.DeleteWishView.as_view(), name='delete_from_wish')
]

core/store/models.py
from PIL import Image

from django.db import models
from django.urls import reverse

from multiselectfield import MultiSelectField


def get_product_url(obj, view_name):
    """ Get custom product url """

    ct_model = obj.__class__._meta.model_name
    return reverse(view_name, kwargs={'ct_model': ct_model, 'product_slug': obj.slug})


def get_models_for_count(*model_names):
    """ Get count of models """

    return [models.Count(model_name) for model_name in model_names]


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass


class Category(models.Model):
    """ Category model """

    name = models.CharField(max_length=255,
                            verbose_name="Ім'я категорії")
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Категорії'
        verbose_name = "Категорію"

    def __str__(self):
        return self.name


class Brand(models.Model):
    """ Brand model """

    name = models.CharField(max_length=255, verbose_name="Назва")
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Бренди'
        verbose_name = "Бренд"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("store:product_list_by_brand", kwargs={"brand_slug": self.slug})


class Product(models.Model):
    """ Template of product model """

    MIN_RESOLUTION = (200, 200)
    MAX_RESOLUTION = (700, 700)

    class Meta:
        abstract = True

    name = models.CharField(max_length=255, verbose_name="Назва")
    slug = models.SlugField(max_length=255, unique=True)
    price = models.DecimalField(
        max_digits=9, decimal_places=2, verbose_name="Ціна")
    discount_price = models.DecimalField(
        max_digits=9, decimal_places=2, verbose_name="Знижка", blank=True, null=True)
    description = models.TextField(blank=True, verbose_name="Опис")
    image = models.ImageField(upload_to='products', verbose_name='Зображення')
    brand = models.ForeignKey(
        Brand, on_delete=models.SET_NULL, verbose_name='Бренд', null=True)

    in_stock = models.BooleanField(default=True, verbose_name="В наявності")
    is_active = models.BooleanField(default=True, verbose_name="Активне")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Створено")
    updated = models.DateTimeField(auto_now=True, verbose_name="Оновлено")

    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)
        min_height, min_width = self.MIN_RESOLUTION
        max_height, max_width = self.MAX_RESOLUTION
        if img.height < min_height or img.width < min_width:
            raise MinResolutionErrorException(
                'Розмір зображення менше мінімального! ')
        if img.height > max_height or img.width > max_width:
            raise MaxResolutionErrorException(
                'Розмір зображення більший максимально дозволеного! ')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_model_name(self):
        return self.__class__.__name__.lower()


"""
    Products classes with speciffic settings that inherit from class product
"""


class ShoesProduct(Product):
    """ Shoes product model """

    SHOES_SIZE = [
        ('40', '40'),
        ('41', '41'),
        ('42', '42'),
        ('43', '43'),
        ('44', '44'),
        ('45', '45'),
    ]

    available_size = MultiSelectField(
        max_length=12, max_choices=5, choices=SHOES_SIZE, verbose_name="Розміра в наявності")
    category = models.ForeignKey(
        Category, related_name='shoes_product', on_delete=models.CASCADE, verbose_name="Категорія")

    class Meta:
        verbose_name_plural = 'Взуття'
        verbose_name = "Продукт - Взуття"

    def get_absolute_url(self):
        return get_product_url(self, 'store:product_detail')


class ClothesProduct(Product):
    """ Clothes product model """

    CLOTHER_SIZE = [
        ('XXL', 'XXL'),
        ('XL', 'XL'),
        ('L', 'L'),
        ('M', 'M'),
        ('S', 'S'),
    ]

    available_size = MultiSelectField(
        max_length=12, max_choices=5, choices=CLOTHER_SIZE, verbose_name="Розміра в наявності")
    category = models.ForeignKey(
        Category, related_name='clothes_product', on_delete=models.CASCADE, verbose_name="Категорія")

    class Meta:
        verbose_name_plural = 'Одяг'
        verbose_name = "Продукт - Одяг"

    def get_absolute_url(self):
        return get_product_url(self, 'store:product_detail')


class BagProduct(Product):
    """ Bag product model """

    size = models.CharField(
        max_length=155, verbose_name="Розмір", default='Один розмір')
    category = models.ForeignKey(
        Category, related_name='bag_product', on_delete=models.CASCADE, verbose_name="Категорія")

    class Meta:
        verbose_name_plural = 'Рюкзаки'
        verbose_name = "Продукт - Рюкзаки"

    def get_absolute_url(self):
        return get_product_url(self, 'store:product_detail')


class AccessoriesProduct(Product):
    """ Accessories product model """

    size = models.CharField(
        max_length=155, verbose_name="Розмір", default='Один розмір')
    category = models.ForeignKey(
        Category, related_name='accessories_product', on_delete=models.CASCADE, verbose_name="Категорія")

    class Meta:
        verbose_name_plural = 'Аксесуари'
        verbose_name = "Продукт - Аксесуари"

    def get_absolute_url(self):
        return get_product_url(self, 'store:product_detail')

core/store/forms.py
from django import forms


class SearchForm(forms.Form):
    search_field = forms.CharField(max_length=100, widget=forms.TextInput(
        attrs={'placeholder': 'Пошук...', 'maxlength': 30}))

core/store/views.py
from django.conf import settings
from django.shortcuts import render
from django.views.generic import DetailView, View
from django.core.paginator import Paginator


from . import models
from .forms import SearchForm
from .services import ProductSystem


def search_product(request):
    """ Search products by request """

    categories = ProductSystem.get_categories(self=ProductSystem)
    brands = ProductSystem.get_brands()
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            search_request = form.cleaned_data['search_field']
            products = ProductSystem.search_products_by_request(
                self=ProductSystem,
                search_request=search_request)
    else:
        form = SearchForm()
    paginator = Paginator(products, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'store/products/products.html', {'products': page_obj,
                                                            'categories': categories,
                                                            'brands': brands,
                                                            'search_form': form,
                                                            })


class BaseView(View):
    """ Show main page """

    def get(self, request):
        products = ProductSystem.get_product_list_with_discount(
            self=ProductSystem,
            models=settings.PRODUCT_MODELS
        )
        return render(request, 'store/homepage.html', {'discount_products': products, })


class ProductListView(View):
    """ Show product list """

    def get(self, request, **kwargs):
        products = ProductSystem.get_product_list(
            models=settings.PRODUCT_MODELS
        )
        categories = ProductSystem.get_categories(self=ProductSystem)
        brands = ProductSystem.get_brands()
        search_form = SearchForm()

        if kwargs.get('category_slug'):
            category_slug = kwargs.get('category_slug')
            products = ProductSystem.get_product_list_by_category(self=ProductSystem,
                                                                  category_slug=category_slug,
                                                                  models=settings.PRODUCT_MODELS)

        if kwargs.get('brand_slug'):
            brand_slug = kwargs.get('brand_slug')
            products = ProductSystem.get_products_by_brand(self=ProductSystem, brand_slug=brand_slug,
                                                           models=settings.PRODUCT_MODELS)

        if kwargs.get('min_price'):
            min_price, max_price = kwargs.get(
                'min_price'), kwargs.get('max_price')
            products = ProductSystem.get_product_list_by_price(self=ProductSystem,
                                                               min_price=min_price,
                                                               max_price=max_price,
                                                               models=settings.PRODUCT_MODELS)
        paginator = Paginator(products, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'store/products/products.html', {'products': page_obj,
                                                                'categories': categories,
                                                                'brands': brands,
                                                                'search_form': search_form,
                                                                })


class ProductDetailView(DetailView):
    """ Show product detail page """

    CT_MODEL_MODEL_CLASS = {
        'clothesproduct': models.ClothesProduct,
        'shoesproduct': models.ShoesProduct,
        'bagproduct': models.BagProduct,
        'accessoriesproduct': models.AccessoriesProduct,
    }

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_MODEL_CLASS[kwargs['ct_model']]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ct_model'] = self.model._meta.model_name
        category_slug = context['product'].category.slug
        context['related_products'] = ProductSystem.get_product_list_by_category(self=ProductSystem,
                                                                                 category_slug=category_slug,
                                                                                 models=settings.PRODUCT_MODELS)
        context['related_products'].remove(context['product'])
        return context

    context_object_name = 'product'
    template_name = 'store/products/product_detail.html'
    slug_url_kwarg = 'product_slug'

core/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Male fashion.{% endblock title %}</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
        rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>
<!-- Header Section Begin -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'store:home_page' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li {% if request.path == '/' %} class="active"{% endif %}><a href="{% url 'store:home_page' %}">Головна</a></li>
                        <li {% if 'products/' in request.path %} class="active"{% endif %}><a href="{% url 'store:products_list' %}">Список Продуктів</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="{% url 'wish:wish' %}"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                    <a href="{% url 'accounts:account' %}"><img src="{% static 'img/icon/user.png' %}"></a>
                    <a href="{% url 'cart:cart' %}"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span
                            style='color:red; font-weight:900;'>{{cart_products_count}}</span></a>
                    
                    <div class="price">{{cart_final_price}} грн.</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->
{% if messages %}
<div class="alert alert-success alert-dismissible fade show container" role="alert">
    {% for message in messages %}
    <strong>{{message}}</strong>
    {% endfor %}
    <button class="close" data-dismiss="alert" arial-lable="Close">
        <span aeia-hidden="true">&times;</span>
    </button>
</div>
{% endif %}
{% block content %}{% endblock content %}

<!-- Footer Section Begin -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a>
                    </div>
                    <p>The customer is at the heart of our unique business model, which includes design.</p>
                    <a href="#"><img src="{% static 'img/payment.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Clothing Store</a></li>
                        <li><a href="#">Trending Shoes</a></li>
                        <li><a href="#">Accessories</a></li>
                        <li><a href="#">Sale</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Payment Methods</a></li>
                        <li><a href="#">Delivary</a></li>
                        <li><a href="#">Return & Exchanges</a></li>
                    </ul>
                </div>
            </div>
            
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="footer__copyright__text">
                    Created by Denis Danchyk
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->



<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

core/templates/store/homepage.html
{% extends './base.html' %}

{% load static %}

{% block content %}
<!-- Hero Section Begin -->
<section class="hero">
    <div class="hero__slider owl-carousel">
        <div class="hero__items set-bg" data-setbg="{% static 'img/hero/hero-1.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-7 col-md-8">
                        <div class="hero__text">
                            <h6>Літня колекція</h6>
                            <h2>Осіня - Зимова колекції 2021</h2>
                            <a href="{% url 'store:products_list' %}" class="primary-btn">Придбати зараз <span
                                    class="arrow_right"></span></a>
                            <div class="hero__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="hero__items set-bg" data-setbg="{% static 'img/hero/hero-2.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-7 col-md-8">
                        <div class="hero__text">
                            <h6>Літня колекція</h6>
                            <h2>Осіня - Зимова колекції 2021</h2>
                            <a href="{% url 'store:products_list' %}" class="primary-btn">Придбати зараз <span
                                    class="arrow_right"></span></a>
                            <div class="hero__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Hero Section End -->

<!-- Banner Section Begin -->
<section class="banner spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 offset-lg-4">
                <div class="banner__item">
                    <div class="banner__item__pic">
                        <img src="{% static 'img/banner/banner-1.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Колекція одягу</h2>
                        <a href="{% url 'store:products_list' %}">Придбати зараз</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="banner__item banner__item--middle">
                    <div class="banner__item__pic">
                        <img src="{% static 'img/banner/banner-2.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Аксесуари</h2>
                        <a href="{% url 'store:products_list' %}">Придбати зараз</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="banner__item banner__item--last">
                    <div class="banner__item__pic">
                        <img src="{% static 'img/banner/banner-3.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Літнє взуття 2021</h2>
                        <a href="{% url 'store:products_list' %}">Придбати зараз</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Banner Section End -->

<!-- Product Section Begin -->
{% if discount_products %}
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="filter__controls">
                    <li class="active" data-filter=".new-arrivals">Гарячі пропозиції</li>
                </ul>
            </div>
        </div>
        <div class="row product__filter">
            {% for product in discount_products %}
            <div class="col-lg-3 col-md-6 col-sm-6">
                <form action="{% url 'cart:add_to_cart' ct_model=product.get_model_name product_slug=product.slug %}"
                    method='POST'>{% csrf_token %}
                    <div class="product__item">
                        <div class="product__item__pic set-bg"
                            data-setbg="{% if product.image %}{{product.image.url}}{% else %}{% static 'img/default/default.jpg'%}{% endif %}">
                            {% if product.discount_price %}
                            <span class="label"><b>Знижена ціна!</b></span>
                            {% endif %}
                            <ul class="product__hover">
                                <li><a
                                        href="{% url 'wish:add_to_wish' ct_model=product.get_model_name product_slug=product.slug %}"><img
                                            src="{% static 'img/icon/heart.png' %}" alt=""></a></li>
                                </li>
                                <li><a href="{{product.get_absolute_url}}"><img src="{% static 'img/icon/search.png' %}"
                                            alt=""></a>
                                </li>
                            </ul>
                        </div>
                        <div class="product__item__text">
                            <h6>{{product.name|title}} {{product.brand}}</h6>
                            <input style="color:red;" type="submit" class="btn add-cart" value="+ Добавити в корзин">

                            <div class="rating">
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                            </div>
                            {% if product.discount_price %}
                            <h5>{{product.discount_price}} грн</h5>
                            {% else %}
                            <h5>{{product.price}} грн</h5>
                            {% endif %}
                        </div>
                    </div>
                </form>
            </div>
            {% endfor %}
        </div>

    </div>
    </div>
</section>
{% endif %}
<!-- Product Section End -->

<!-- Categories Section Begin -->
<section class="categories spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="categories__text">
                    <h2>Колекція одягу <br /> <span>Взуття</span> <br />Аксесуари</h2>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="categories__hot__deal">
                    <img src="{% static 'img/product-sale.png' %}" alt="">
                    <div class="hot__deal__sticker">
                        <span>Знижка</span>
                        <h5>799 грн</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-1">
                <div class="categories__deal__countdown">
                    <span>Пропозиція тижня</span>
                    <h2>Рюкзак</h2>
                    <div class="categories__deal__countdown__timer" id="countdown">
                        <div class="cd-item">
                            <span>3</span>
                            <p>Дні</p>
                        </div>
                        <div class="cd-item">
                            <span>1</span>
                            <p>Години</p>
                        </div>
                        <div class="cd-item">
                            <span>50</span>
                            <p>Хвилини</p>
                        </div>
                        <div class="cd-item">
                            <span>18</span>
                            <p>Секунди</p>
                        </div>
                    </div>
                    <a href="{% url 'store:products_list' %}" class="primary-btn">Купити зараз</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Categories Section End -->

<!-- Instagram Section Begin -->
<section class="instagram spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="instagram__pic">
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-1.jpg' %}">
                    </div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-2.jpg' %}">
                    </div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-3.jpg' %}">
                    </div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-4.jpg' %}">
                    </div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-5.jpg' %}">
                    </div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-6.jpg' %}">
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="instagram__text">
                    <h2>Instagram</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua.</p>
                    <h3>#Male_Fashion</h3>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Instagram Section End -->

{% endblock content %}