core/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from . import views
from .forms import UserLoginForm

app_name = 'accounts'

urlpatterns = [
    path('', views.AccountPage.as_view(), name='account'),
    path('personal_information/', views.AccountPersonalInformation.as_view(), name='personal_information'),
    path('personal_orders/', views.AccountPersonalOrders.as_view(), name='personal_orders'),
    path('edit_information/', views.EditPersonalInformation.as_view(), name='edit_information'),


    path('registration/', views.AccountRegistrationView.as_view(),
         name='account_registration'),
    path('activate/<slug:uidb64>/<slug:token>)/',
         views.account_activate, name='activate_account'),
    path('login/', auth_view.LoginView.as_view(template_name='accounts/registration/login.html',
         form_class=UserLoginForm), name='login'),
    path('logout/', auth_view.LogoutView.as_view(next_page='/account/login/'), name='logout'),
]

core/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add-to-cart/<slug:ct_model>/<slug:product_slug>',
         views.AddToCartView.as_view(), name='add_to_cart'),
    path('delete-from-cart/<slug:ct_model>/<slug:product_slug>/',
         views.DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-product-quantity/<slug:ct_model>/<slug:product_slug>/',
         views.ChangeQuantityView.as_view(), name='change_product_quantity'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='card')),
    path('order/', include('orders.urls', namespace='orders')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/orders/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'orders'


urlpatterns = [
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('create_order/', views.CreateOrderView.as_view(), name='create_order'),
    path('invalid_order/', TemplateView.as_view(template_name='orders/order_invalid.html'), name='invalid_order'),

]

core/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.BaseView.as_view(), name='home_page'),

    path('search/', views.search_product, name='search'),

    path('products/', views.ProductListView.as_view(), name='products_list'),

    path('products/price/<str:min_price>/<str:max_price>/',
         views.ProductListView.as_view(), name='product_list_by_price'),


    path('products/category/<slug:category_slug>/',
         views.ProductListView.as_view(), name='product_list_by_category'),

    path('products/brand/<slug:brand_slug>/', views.ProductListView.as_view(),
         name='product_list_by_brand'),



    path('product/<slug:ct_model>/<slug:product_slug>/',
         views.ProductDetailView.as_view(), name='product_detail'),
]

core/orders/models.py
from django.db import models
from django.utils import timezone

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from cities_light.models import City

from cart.models import *
from accounts.models import *


class OrderItem(models.Model):
    """ Item model for order """

    order = models.ForeignKey(
        'Order', on_delete=models.CASCADE, verbose_name="Замовлення")

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    price = models.DecimalField(
        max_digits=9, decimal_places=2, verbose_name="Ціна")
    quantity = models.PositiveIntegerField(default=1, verbose_name="Кількість")

    def __str__(self):
        return str(self.id)


class Order(models.Model):
    """ Order model """

    STATUS_CHOICES = (
        ("STATUS_NEW", "Нове замовлення"),
        ("STATUS_IN_PROCESS", "Замовлення в процесі обробки"),
        ("STATUS_READY", "Замовлення готове"),
        ("STATUS_COMPLETED", "Замовлення виконане"),
    )

    BYING_TYPE = (
        ("BYING_TYPE_SELF", "Самовивіз"),
        ("BYING_TYPE_DELIVERY", "Доставка"),
    )

    customer = models.ForeignKey(
        'accounts.UserBase', on_delete=models.CASCADE, related_name="related_orders", verbose_name='Покупець')
    cart = models.ForeignKey(
        'cart.Cart', on_delete=models.CASCADE, verbose_name="Корзина", null=True
    )
    first_name = models.CharField(max_length=255,  verbose_name="Ім'я")
    last_name = models.CharField(max_length=255,  verbose_name="Фамілія")
    phone = models.CharField(max_length=255,  verbose_name="Номер телефону")
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name="Місто")
    post_office = models.CharField(
        max_length=255, verbose_name="Вдділення пошти")
    email = models.EmailField()
    comment = models.TextField(
        null=True, blank=True, verbose_name="Комментар до замовлення")

    status = models.CharField(
        max_length=255, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][1], verbose_name="Статус")

    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата створення замовлення")
    order_date = models.DateTimeField(
        default=timezone.now, verbose_name="Дата доставки товару покупцю")

    class Meta:
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'

    def __str__(self):
        return str(self.id)

core/orders/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField

from orders.models import Order


class OrderForm(forms.ModelForm):
    phone = PhoneNumberField(widget=forms.TextInput(
        attrs={'placeholder': '+380(11)9999999', 'maxlength': 16}))
    phone.error_messages[
        'invalid'] = 'Введіть коректний номер телефону (наприклад, +380(11)9999999).'

    class Meta:
        model = Order
        widgets = {
            'first_name': forms.TextInput(
                attrs={'placeholder': "Ім'я", 'maxlenght': 30}
            ),
            'last_name': forms.TextInput(
                attrs={'placeholder': 'Фамілія', 'maxlenght': 30}
            ),
            'email': forms.TextInput(
                attrs={'placeholder': 'Email', 'maxlenght': 50}
            ),
            'post_office': forms.TextInput(
                attrs={'placeholder': 'Номер пошти', 'maxlenght': 4}
            ),
            'comment': forms.TextInput(
                attrs={
                    'placeholder': 'Вкажіть додатвоку інформацію, якщо це необхідно', 'maxlenght': 250}
            ),
        }
        fields = ('first_name', 'last_name', 'phone',
                  'email', 'city', 'post_office', 'comment')

    def clean_post_office(self):
        post_office = self.cleaned_data['post_office']
        for i in post_office:
            try:
                int(i)
            except ValueError:
                raise forms.ValidationError(
                    "Номер пошти повинен складатися лише з цифр!")
        return post_office

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        for i in first_name:
            try:
                int(i)
                raise forms.ValidationError(
                    "В імені не повинно бути цифр!")
            except ValueError:
                pass
        return first_name
    
    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        for i in last_name:
            try:
                int(i)
                raise forms.ValidationError(
                    "В фімілії не повинно бути цифр!")
            except ValueError:
                pass
        return last_name

core/orders/views.py
from django.shortcuts import render, redirect
from django.views.generic import View

from cart.mixins import CartMixin
from cart.services import CartSystem
from coupons.services import CouponSystem


from .services import OrderSystem
from .forms import OrderForm


class CheckoutView(View):
    """ Show checkout page """

    def get(self, request):
        form = OrderForm()
        cart = CartSystem.get_customer_cart(request)
        cart_products = CartSystem.get_cart_products(cart=cart)
        coupons = CouponSystem.get_coupons_applied_to_cart(cart=cart)

        return render(request, 'orders/checkout.html', {'form': form,
                                                        'cart_products': cart_products,
                                                        'cart': cart,
                                                        'coupons': coupons})


class CreateOrderView(CartMixin, View):
    """ Create order """

    def post(self, request):
        form = OrderForm(request.POST)
        form, success = OrderSystem.create_order(
            self=OrderSystem, form=form, cart=self.cart)
        if form.errors:
            cart = CartSystem.get_customer_cart(request)
            cart_products = CartSystem.get_cart_products(cart=cart)
            return render(request, 'orders/checkout.html', {'form': form,
                                                            'cart_products': cart_products,
                                                            'cart': cart})
        if success:
            return render(request, 'orders/order_valid.html')
        else:
            return redirect('/order/invalid_order/')

core/templates/orders/checkout.html
{% extends '../store/base.html' %}
{% block content %}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Оформлення замовлення</h4>
                    <div class="breadcrumb__links">
                        <a href="{% url 'store:products_list' %}">Продукти</a>
                        <a href="{% url 'cart:cart' %}">Корзина</a>
                        <span>Оформлення замовлення</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Checkout Section Begin -->
<section class="checkout spad">
    <div class="container">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% endif %}
        <div class="checkout__form">
            <form action="{% url 'orders:create_order' %}" method="POST">{% csrf_token %}
                <div class="row">
                    <div class="col-lg-8 col-md-6">
                        <h6 class="checkout__title">Ваші данні</h6>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Ім'я<span>*</span></p>
                                    {{form.first_name}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Фамілія<span>*</span></p>
                                    {{form.last_name}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Номер телефону<span>*</span></p>
                                    {{form.phone}}
                                    <h6>(після замовлення з вами зв'яжутьсяя наш менеджер)</h6>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Email<span>*</span></p>
                                    {{form.email}}
                                </div>
                            </div>
                        </div>
                        <div class="checkout__input">
                            <p>Коментар до замовлення<span>*</span></p>
                            {{form.comment}}
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                     <p>Номер пошти<span>*</span></p>
                                    {{form.post_office}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input dropdown-cities">
                                    <p>Місто<span>*</span></p>
                                    {{form.city}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="checkout__order">
                            <h4 class="order__title">Ваше замовлення</h4>
                            <div class="checkout__order__products">Продукт/Кількість<span>Ціна</span></div>
                            <ul class="checkout__total__products">
                                {% for cart_product in cart_products %}
                                <li>{{forloop.counter}}.
                                    {{cart_product.content_object.name}}
                                    x{{cart_product.quantity}}<span>
                                        {% if cart_product.content_object.discount_price %}
                                        {{cart_product.content_object.discount_price }}
                                        {% else %}{{cart_product.content_object.price }}грн{% endif %}</span>
                                </li>
                                {% endfor %}
                            </ul>
                            <ul class="checkout__total__all">
                                 {% if coupons %}
                                <h6>Застосовані купони</h6>
                                <hr>
                                <ul>
                                    {% for coupon in coupons %}
                                    <li>Купон "{{coupon}}"<span>Знижка - {{coupon.discount}}%</span></li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                                <hr>
                                <li>Всього <span>{{cart.final_price}} грн</span></li>
                            </ul>
                            <input type="submit" class="site-btn" value='Оформити замовлення'>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<hr>
<!-- Checkout Section End -->
{% endblock content %}

core/templates/orders/order_invalid.html
{% extends '../store/base.html' %}
{% block content %}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Оформлення замовлення</h4>
                    <div class="breadcrumb__links">
                        <a href="{% url 'store:products_list' %}">Продукти</a>
                        <a href="{% url 'cart:cart' %}">Корзина</a>
                        <span>Оформлення замовлення</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Checkout Section Begin -->
<section class="checkout spad">
    <div class="container">
        <div class="checkout__form">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>Неможливо оформити замовлення, так як корзина порожня :(</h1>
                    <span><a href="{% url 'accounts:personal_orders' %}">Мої замовлення</a></span> 
                </div>
            </div>
        </div>
    </div>
</section>
<hr>
<!-- Checkout Section End -->
{% endblock content %}

core/templates/orders/order_valid.html
{% extends '../store/base.html' %}
{% block content %}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Оформлення замовлення</h4>
                    <div class="breadcrumb__links">
                        <a href="{% url 'store:products_list' %}">Продукти</a>
                        <a href="{% url 'cart:cart' %}">Корзина</a>
                        <span>Оформлення замовлення</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Checkout Section Begin -->
<section class="checkout spad">
    <div class="container">
        <div class="checkout__form">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>Замовлення було успішно створено!</h1>
                    <span><a href="{% url 'accounts:personal_orders' %}">Мої замовлення</a></span> 
                </div>
            </div>
        </div>
    </div>
</section>
<hr>
<!-- Checkout Section End -->
{% endblock content %}